-- Canoskhi — Supabase (Postgres) kurulumu
-- Supabase Dashboard > SQL Editor > New query > bunu yapistir > Run
-- Tek seferliktir; tablolar + erisim kurallari kurulur.

CREATE TABLE IF NOT EXISTS customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ad_soyad TEXT NOT NULL,
  telefon TEXT,
  eposta TEXT,
  dogum_tarihi TEXT,
  dogum_yeri TEXT,
  notlar TEXT,
  durum TEXT DEFAULT 'aktif',
  musteri_baslangic TEXT,
  foto TEXT,
  created_at TEXT DEFAULT (CURRENT_DATE::TEXT)
);

CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ad TEXT NOT NULL UNIQUE,
  kategori TEXT
);

CREATE TABLE IF NOT EXISTS customer_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id),
  product TEXT,
  tutar DOUBLE PRECISION DEFAULT 0,
  anapara DOUBLE PRECISION DEFAULT 0,
  guncel_deger DOUBLE PRECISION DEFAULT 0,
  guncel_tarih TEXT,
  prim_tutar DOUBLE PRECISION DEFAULT 0,
  prim_durumu TEXT DEFAULT 'bekleyen',
  baslangic_tarihi TEXT,
  bitis_tarihi TEXT,
  durum TEXT DEFAULT 'aktif',
  iptal_tarihi TEXT,
  iptal_nedeni TEXT,
  oto_yenile INTEGER DEFAULT 1,
  yenileme_kaynagi TEXT
);

CREATE TABLE IF NOT EXISTS incomes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kaynak TEXT NOT NULL,
  tutar DOUBLE PRECISION NOT NULL,
  tarih TEXT NOT NULL,
  aciklama TEXT,
  customer_id BIGINT REFERENCES customers(id),
  cprod_id BIGINT REFERENCES customer_products(id)
);

CREATE TABLE IF NOT EXISTS expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kategori TEXT NOT NULL,
  tutar DOUBLE PRECISION NOT NULL,
  tarih TEXT NOT NULL,
  aciklama TEXT
);

CREATE TABLE IF NOT EXISTS reminders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  baslik TEXT NOT NULL,
  tarih TEXT,
  tip TEXT DEFAULT 'is',
  oncelik TEXT DEFAULT 'normal',
  customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
  tamamlandi INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  baslik TEXT,
  icerik TEXT,
  tip TEXT DEFAULT 'sahsi',
  customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
  tarih TEXT,
  created_at TEXT DEFAULT (CURRENT_DATE::TEXT)
);

CREATE TABLE IF NOT EXISTS mail_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
  eposta TEXT NOT NULL,
  konu TEXT,
  icerik TEXT,
  tarih TEXT,
  durum TEXT DEFAULT 'taslak'
);

CREATE TABLE IF NOT EXISTS documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  ad TEXT NOT NULL,
  tip TEXT DEFAULT 'diger',
  tarih TEXT,
  notlar TEXT,
  dosya_ad TEXT,
  dosya_tip TEXT,
  dosya_veri TEXT
);

CREATE TABLE IF NOT EXISTS savings_goals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ad TEXT NOT NULL,
  tip TEXT DEFAULT 'hedef',
  kisi TEXT,
  hedef_tutar DOUBLE PRECISION DEFAULT 0,
  biriken DOUBLE PRECISION DEFAULT 0,
  tarih TEXT,
  notlar TEXT
);

CREATE TABLE IF NOT EXISTS subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ad TEXT NOT NULL,
  tutar DOUBLE PRECISION DEFAULT 0,
  odeme_gunu INTEGER DEFAULT 1,
  periyot TEXT DEFAULT 'aylik',
  ay INTEGER DEFAULT 1,
  kategori TEXT,
  aktif INTEGER DEFAULT 1,
  son_odeme TEXT
);

CREATE TABLE IF NOT EXISTS special_days (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ad TEXT NOT NULL,
  tarih TEXT NOT NULL,
  tip TEXT DEFAULT 'diger',
  tekrar TEXT DEFAULT 'yillik',
  oncelik TEXT DEFAULT 'normal',
  tamamlandi INTEGER DEFAULT 0,
  notlar TEXT
);

CREATE TABLE IF NOT EXISTS personal_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  baslik TEXT NOT NULL,
  tarih TEXT,
  oncelik TEXT DEFAULT 'normal',
  tamamlandi INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS prim_goals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ay TEXT UNIQUE NOT NULL,
  hedef DOUBLE PRECISION DEFAULT 0
);

-- Erisim: tek kisilik kisisel uygulama, anahtarla acik erisim
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE incomes ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE reminders ENABLE ROW LEVEL SECURITY;
ALTER TABLE notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE mail_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE savings_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE special_days ENABLE ROW LEVEL SECURITY;
ALTER TABLE personal_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE prim_goals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "open" ON customers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "open" ON products FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "open" ON customer_products FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "open" ON incomes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "open" ON expenses FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "open" ON reminders FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "open" ON notes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "open" ON mail_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "open" ON documents FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "open" ON savings_goals FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "open" ON subscriptions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "open" ON special_days FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "open" ON personal_tasks FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "open" ON prim_goals FOR ALL USING (true) WITH CHECK (true);
